### ISSUE TITLE
nuget packages

### ISSUE THREAD

**Issue by konne** [NetOfficeFw/NetOffice#13]
Hi,

what is you plan to release nuget packages?

bye Konrad

**Comment by jozefizso** [comment]
Hi @konne,
I would love to publish latest releases of NetOffice to NuGet server. The problem is the NuGet packages are owned by Caio Proiete and he refuses to communicate with Sebastian (current NetOffice developer and maintainer) and/or me. That's also reason why NetOffice library exists here and not under the https://github.com/netoffice organization.

We tried to contant Caio using GitHub, e-mail and Skype but he refused to do anything about NetOffice.

I'm still not sure how we will resolved this issue with NuGet packages, but most probably we would have to release the NetOffice library using new package names.

**Comment by konne** [comment]
Hi @jozefizso,
thanks for your answers. I know Caio because of ExcelDNA and I can understand that he is after frustrating discussion with sebastion http://netoffice.codeplex.com/discussions/459528  a little bit uncommunicative.
I try to get in touch with him and will discuss how we can solve this issue.
bye Konrad

**Comment by jozefizso** [comment]
Great!

**Comment by jozefizso** [comment]
I know Sebastian did not supported NuGet packages. It's great we had the NuGet packages available from Caio.

But I don't think this is the reason to not communicate at all with project maintainers about any aspect of future development of the library (especially in case of squatting the project' official name).

As NetOffice will live on GitHub from now on, I fully support having official NuGet packages because it's the best way to manage and distribute such complex libraries.

**Comment by konne** [comment]
Hi, I had just a conversation and because of the difficulty between Caio and Sebastian and you I would prefer that we make it simple. You / me make pull requests against Caio repo with 1.7.4 updates. He is willing to accept it and we will after that update the nuget packages.
In the past, a lot of trust has been destroyed and it will take some time to let things develop in a common direction.

**Comment by jozefizso** [comment]
Yes, I agree the trust had been destroyed, especially after deleting this whole thread: https://github.com/netoffice/NetOffice/issues/3

As Caio owns NetOffice NuGets packages, it's up to him to make new version available.

I hope it's understandable I personally won't invest my time in making a pull request to Caio's repository as his actions proved he is not willing to communicate/maintain stuff related to the project.

**Comment by konne** [comment]
Fingerpointing is very easy and I tried to find a way to get slowly the situation on a better way, but I see at the moment no willing from your side and so I will close that case from my side.
If you maybe change your mind just ping me again and I try to arrange in the future maybe a new compromise.

**Comment by jozefizso** [comment]
We released **NetOffice 1.7.4.x** packages under the [netoffice](https://www.nuget.org/profiles/netoffice) account on nuget.org. They are available with a new name [NetOfficeFw](https://www.nuget.org/packages?q=NetOfficeFw)

The **NetOfficeFw** are the official releases (**1.7.4.1** and **1.7.4.3** at the moment) and contain official libraries with source code and debugging information.

On contrary, all old [NetOffice](https://www.nuget.org/packages?q=NetOffice) packages were deleted (the 1.6.0, 1.7.2 and 1.7.3 are no longer available) and a rogue NetOffice packages were published under version 1.7.4.4 - these contain the 1.7.3 assemblies - so they mislead developers.

![screenshot_052818_035026_pm](https://user-images.githubusercontent.com/287778/40617543-e24fa584-628e-11e8-9208-737147e3793f.jpg)

**Comment by jozefizso** [comment]
We publish official packages under the **netoffice** profile on NuGet now.

https://www.nuget.org/profiles/netoffice
