### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by nobisheikh** [NetOfficeFw/NetOffice#16]
Hello,

I have couple general questions about NetOffice, I couldn't find a better place to put it since it's not an issue.

- I read a brief history with what's going on with nuget package and this repo on one of the other issues. Are we saying that what's in nuget is different from what's in here? Who has the latest? Are both getting maintained? We are looking to use NetOffice is couple high profile projects so I am trying to understand what's stable, what's reliable and what's the latest. 

- Are there any functional differences in say what Excel 2016 interop can do vs NetOffice?

Sorry if these questions are redundant and have been answered before, just trying to understand some history before using the library for production applications.

Thanks,

- Nabeel

**Comment by jozefizso** [comment]
You will find NetOffice library in NuGet. The latest available version there is 1.7.3 which works great. Those files in NuGet should match what you will find here in ZIP/RAR files under Releases. NetOffice 1.7.3 is production ready, it's very stable and covers all the APIs of MS Office applications.

There is also newer NetOffice 1.7.4 available. This one is not published to NuGet yet. I'm a big fan of NuGet and I would love to see latest NetOffice there. Because of the communication/blackmailing issues with the maintainer of the NuGet packages, we will most probably release these packages under new name. I still haven't had time to do.

Speaking of plain Intertop libraries, there should be no difference between Excel 2016 Interop and NetOffice 1.7.3 and/or 1.7.4.x - all the APIs should be available, although you may need to rewrite names of events, because NetOffice uses different naming conventions then Interop.

The project is now in the process of moving from CodePlex. I'm in touch with Sebastian, who writes the code and maintains it. Sebastian loves Subversion so he chose the OSDN to host his latest source code. We agreed I will maintain the project on GitHub as it is popular service.
