### ISSUE TITLE
AppEvents

### ISSUE THREAD

**Issue by matteshe** [NetOfficeFw/NetOffice#194]
In the download Version 1.7.4.3 one find AppEvents.cs under Source/Excel/Events/ with namespace NetOffice.ExcelApi.Events and on the source tree in github under Source/Excel/EventInterfaces with namespace NetOffice.ExcelApi. The commit was a year ago and saying "Imported NetOffice 1.7.4-alpha source code". Does the classes in this folder move without commit?

**Comment by jozefizso** [comment]
The imported code is taken directly from the Subversion repository ([OSDN](https://osdn.net/projects/netoffice/scm/svn/) nowadays, it was CodePlex before). The source code should match what you find in the related SVN commit.

This may not match the code in the ZIP package though. The ZIP packages are taken from the [OSDN releases](https://osdn.net/projects/netoffice/releases/) and I noticed the code in `Sources` may not match what is in Subversion repository.

I think Sebastian is making release builds from the source code on disk and he sometimes forgets to make commit before making a release and that's why there are discrepancies.

**Comment by jozefizso** [comment]
It's also possible I made mistake when importing the code.
