### ISSUE TITLE
NuGet packages?

### ISSUE THREAD

**Issue by A9G-Data-Droid** [NetOfficeFw/NetOffice#214]
There is a NuGet package for "NetOffice" but it looks like "NetOfficeFw" is more actively developed. 

https://github.com/netoffice/NetOffice-NuGet

Is there a plan to put NetOfficeFw on NuGet?

**Comment by jozefizso** [comment]
NetOffice libraries v1.7.4.x are distributed on NuGet under the NetOfficeFw name. These packages are compiled with the debugging and source code information in them too.

You will find all the packages here: https://www.nuget.org/profiles/netoffice

The latest stable version is 1.7.4.3.

**Comment by A9G-Data-Droid** [comment]
Wow, I don't know how I missed that. Thanks.

**Comment by A9G-Data-Droid** [comment]
What is the difference between these two repos? Now I'm confused. I don't see any statement about the relationship between the two projects.

**Comment by jozefizso** [comment]
NetOffice repositories and NuGet package have quite complicated history.

The original project was developed on Codeplex and because the service was about to shutdown and the project looked abandoned, it had to be moved somewhere. As owner of https://github.com/netoffice/ was not communicating, I decided to create a new hub for the NetOffice project.

Meanwhile original author of NetOffice library got back to the development but in the a new Subversion repository at https://osdn.net/projects/netoffice/

This repository contains the Git mirror of the original source code.

As Sebastian does not like the NuGet, all NetOffice library packages are unofficial. And to publish latest versions, we have to use new names for them as well.

**Comment by samatrhea** [comment]
@SebastianDotNet how do you suggest developers should use the libraries in case nuget is not used? just copy the dll's around and reference them?

**Comment by jozefizso** [comment]
Sebastian's preferred distribution model for NetOffice library was to release ZIP files with assemblies and the related source code.

For the conveniece, NuGet packages were release by other people. If you use the NetOfficeFw nuget packages, you will also a good debugging experience as our packages include the symbol files and source code so Visual Studio is able to use it and you can step into the library while debugging.
