### ISSUE TITLE
Statement in whats wrong in NetOffice and why i leave

### ISSUE THREAD

**Issue by SebastianDotNet** [NetOfficeFw/NetOffice#241]
https://wordpress.com/view/microschuft.wordpress.com

**Comment by samatrhea** [comment]
Dear @SebastianDotNet,

I am sorry to read that you are leaving the project. Would you be able to give an opinion on what a better alternative is than NetOffice to create Office Addins, both open-source or proprietary solution tips would be appreciated.

**Comment by jozefizso** [comment]
Link to the actual blogpost: https://microschuft.wordpress.com/2019/04/16/finaly-block/

**Comment by SRunUp** [comment]
Will the project continue to be maintained?

**Comment by AndreasSummer** [comment]
Can you please explain the problem with the com proxy system.

**Comment by jozefizso** [comment]
> Will the project continue to be maintained?

I try to maintain the project and release bug fixes.

**Comment by jozefizso** [comment]
Hi @Rand-Random, this is open source project provided without any warranties.

You are free to fix the design issue, any PR is welcome.

We are not forcing users to use this library. There are other options like VSTO provided directly by Microsoft.

**Comment by jozefizso** [comment]
@Rand-Random what you should be actually telling/answering to your manager is: Are you willing to fix bugs in open source libraries you are using?

**Comment by semenenkov** [comment]
Hello @jozefizso @SebastianDotNet,

I've read https://microschuft.wordpress.com/2019/04/16/finaly-block/ multiple times and not sure I understand how something can work for a small project and not be not applicable at all for the big one. Where is that limit of applicability and how it can be measured. There is an unanswered question above from @AndreasSummer _Can you please explain the problem with the com proxy system_. Is it caused by GC which is not 100% under our control? 

From blog post: _I can give an example if you want – just ask me._
Can you please provide such an example. That would be very helpful to understand which use cases are applicable for this library and which are not.

@jozefizso you suggest to create PR with a fix. It seems that lot of people are using this library and probably some of them would be happy to create such kind of PR if that's possible. You know better than anyone its internals. I think there would be much more chances to get such PR if you could provide more details on this issue.

**Comment by jozefizso** [comment]
Hi @semenenkov, did you run into issues when using this library?

We are using these libraries in production applications and we did not run into issues which are described in the blog post.

**Comment by semenenkov** [comment]
Hi @jozefizso thank you for reply.

I was migrating 1 or 2 times my codebase from PIA to NetOffice. I have even reported one issue with suggestion for a fix which was accepted (it was not a PR, just few line changes I've mentioned directly in the ticket). It seems to be working, but I did not make these changes live because existing PIA logic was working as well, tested and used by many people. There was only one issue with NetOffice that it would increase my app about 5x-10x in size, I don't remember exact numbers.

My thoughts are getting back to netoffice from time to time by couple of reasons:
1) PIAs not updated, but Office object model grows, one of the recent examples is Field3
2) NetOffice seems to be more under my control than PIA, I can take source code and debug in case of some issues

Today I had another think-about-netoffice-once-a-year day because one of my clients is getting RPC_E_SERVERFAULT error from Access and I am not sure whether it is a really Access issue or some invalid usage from PIA which can be changed somehow. I came here because for the first time I've noticed that there are two repos - NetOffice and NetOfficeFw. I was not sure which one is related to original author (Sebastian), started to search for his relation and finally found this issue.

It's good that it is used in production by you and many others. But the fact that initial author has left this project, has created this issue and wrote that blog post - it is a bit disturbing. So if you could tell what did he mean, what can go wrong and why we should not care about this - that would be really great.

**Comment by jozefizso** [comment]
If you are getting exceptions when using PIA, there is nothing the NetOffice would help as the error comes from Office application. NetOffice is such more flexible wrapper for the API then PIA.

Actually, there is at least one API in PowerPoint which does not work with NetOffice. That is [Application.HWND](https://github.com/NetOfficeFw/NetOffice/blob/main/Source/PowerPoint/DispatchInterfaces/_Application.cs#L506-L512) and other HWND members (see https://github.com/NetOfficeFw/NetOffice/issues/140).

This is a limitation of PowerPoint which does not allow to call this API using late binding and the method name. It only works when it is called directly using dispatch ID. We have a prototype which fixes this but it is a long way to have it production ready.

**Comment by jozefizso** [comment]
> Or tell that you're not aware, once.
I won't be explaining claims made by others.

> Many people just would like to know what it is and will raise this question from time to time.
As I said before, this is open source project provided without any warranties.

**Comment by semenenkov** [comment]
> I won't be explaining claims made by others.
It looks strange but looks like should be enough to stop raising this. Thanks!

**Comment by jozefizso** [comment]
Thanks a lot @semenenkov  for posting Sebastian's answer here.

I can agree, the VSTO is better choice for some projects. Historically, you must install VSTO runtime and this requires administrative privileges. With NetOffice you can just deploy you app or addin for user accounts without admin rights. And this could be more beneficial for small project where you won't have memory issues with retaining COM objects.

Sebastian is right that for complex projects you must have discipline and be aware of COM memory management.

I personally prefer to use ReSharper dotMemory to validate how application is retaining objects. For example in MVVM apps which are using messenger pattern it is easy to forget to use weak references to objects and the whole messenger can blow up the memory. So this problem is not just in NetOffice.
